---
title: Collecting Data on Untappd
author: ''
date: '2017-11-29'
categories:
  - beer
tags:
  - beer
  - data_collection
  - R
  - scraping
  - untappd
slug: collecting-data-on-untappd
draft: yes
weight: 1
---

One of my favorite things is beer[^1]. For me, it's not just a fizzy yellow drink. 

Disclaimer: Yes, I have waited in line outside of a brewery before. And yes, I have been known to annoy friends by using phrases like "this beer's nose" or "a pleasant mouthfeel." That said, I do believe that every beer has a place in the world. Philly's Yeungling and Baltimore's Natty Boh hold as much of a place in my heart as [Oerbier 2007](https://www.beeradvocate.com/beer/profile/201/45309/) and hazy northeast milkshake IPAs. 

One of the best things about living in Philadelphia, and the mid-atlantic for that matter, is that the area has a wonderfully thriving beer scene. This is something I don't have data for, but I feel safe with the hunch that I could go to a brewery within an hour of my home and drink a beer I've never had before. Every Night. It really is a rich scene, folks. 

Anyway, there are so many breweries out here that I want to learn about them, and try to see if I can gain an insight into the Philly beer scene. Perhaps I can learn something about the place that any brewery in Philly holds within the scene? Maybe down the road I can figure out what makes the Philly beer scene unique across the country. Hopefully, it isn't just close proximity to great cheesesteaks!

## What kind of data do I want?

When I started to think about how I would go about getting data on Philadelphian Beer, the first place that I went to was to think about the Philadelphia Breweries. Before I jumped into data, I realized that although the beer scene here is large, there is no way I would be able to learn much by just looking at information about breweries. 

I need to look at the beer they make too!

Okay, so I need information about breweries and about the beer breweries make. Where to find it? 

I've chosen [Untappd](https://untappd.com/). For the unitiated, Untappd is an app that allows users to rate and track beers that they drink, right from their phones. It also allows users to see the ratings of beers and breweries. It's a handy tool for beer nerds that like to track the beers they drink. 


[^1]: So much so that I even make my own beer (and kombucha) under the name [Brain Stem Brewing](https://www.instagram.com/BrainStemBrewing/)